create table if not exists public.project_reactions (
  id bigint generated by default as identity primary key,
  project_slug text not null,
  emoji text not null check (emoji in ('❤️', '🔥', '🌚')),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_slug, emoji, user_id)
);

alter table public.project_reactions enable row level security;

drop policy if exists "Public reaction totals are readable" on public.project_reactions;
drop policy if exists "Users add only their reactions" on public.project_reactions;
drop policy if exists "Users remove only their reactions" on public.project_reactions;

create policy "Public reaction totals are readable"
on public.project_reactions for select
to anon, authenticated
using (true);

create policy "Users add only their reactions"
on public.project_reactions for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users remove only their reactions"
on public.project_reactions for delete
to authenticated
using (auth.uid() = user_id);

create or replace view public.project_reaction_counts
with (security_invoker = true)
as
select project_slug, emoji, count(*)::integer as count
from public.project_reactions
group by project_slug, emoji;

grant select on public.project_reaction_counts to anon, authenticated;
grant select, insert, delete on public.project_reactions to authenticated;
grant select on public.project_reactions to anon;
grant usage, select on sequence public.project_reactions_id_seq to authenticated;
